"""
High-Frequency PINN-LNN for UKDALE NILM
========================================

Extends test_pinn_lnn_ukdale_specific_splits.py with three HF-specific ideas:

  1. Multi-channel HF input (4 features per 6-second timestep):
       - aggregate power  (W)
       - dP/dt            — finite-difference rate of change; captures
                            the sharp switching transients visible at 6s
       - rolling mean     — 10-step (60 s) local baseline
       - rolling std      — 10-step (60 s) local variability / cycling noise

  2. Dilated CNN pre-encoder:
       Three Conv1d+BN+ReLU+MaxPool layers with growing dilation (1→2→4)
       compress the WIN-length window into WIN//8 steps while widening the
       temporal receptive field, so the LNN sees a compact but multi-scale
       summary of the raw HF signal.

  3. Same PINN loss as the original:
       L_total = L_MSE + lambda * L_phys  [+ weighted BCE after warmup]
       L_phys  = mean(ReLU(sum_i(p_hat_i_raw) - P_agg_raw - epsilon))

Architecture:
    Input  (batch, WIN, 4)
         |
    DilatedCNNEncoder  ->  (batch, WIN//8, hidden)
         |
    AdvancedLiquidTimeLayer  (adaptive tau, input-dependent gate)
         |
    LayerNorm(hidden)
         |
    4 x Linear(hidden, 1)  — one head per appliance
         |
    Output (batch, 4)

Data:
    Training  : dataset/UKDALE_HF_train.csv      (House 1, 2014-11-09)
    Validation: dataset/UKDALE_HF_validation.csv (House 1, 2014-12-07)
    Testing   : dataset/UKDALE_HF_test.csv       (House 5, 2014-08-24)
    Generated by preprocess_hf.py — run that first.
"""

import sys
import os
import json
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
from datetime import datetime
from tqdm import tqdm
from sklearn.preprocessing import MinMaxScaler

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'Source Code'))
from utils import calculate_nilm_metrics, save_model


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

EPOCHS        = 80
PATIENCE      = 20
LR            = 1e-3
BATCH         = 32
WIN           = 299      # ~30-min context window (299 * 6 s = ~30 min)
STRIDE        = 2        # step between windows
ROLL_WIN      = 10       # rolling stats window: 10 steps = 60 s

LAMBDA_PHYS   = 0.01
EPSILON_W     = 50.0     # background-load tolerance (W)
WARMUP_EPOCHS = 20       # epochs before physics + BCE losses are added

APPLIANCES = ['dishwasher', 'fridge', 'microwave', 'washing_machine']

# ON/OFF threshold per appliance (Watts)
# Note: House 5 test data shows ~25 W microwave standby and ~14 W washer
# standby — these are faithfully reproduced from the raw .dat files.
THRESHOLDS = {
    'dishwasher':      10.0,
    'fridge':          10.0,
    'microwave':       10.0,
    'washing_machine': 10.0,
}

# Weighted BCE to address class imbalance (0 = disabled)
BCE_LAMBDA = {'dishwasher': 0.5, 'fridge': 0.3, 'microwave': 0.0, 'washing_machine': 0.0}
BCE_ALPHA  = {'dishwasher': 2.0, 'fridge': 2.0, 'microwave': 1.0, 'washing_machine': 1.0}

DATA_DIR = os.path.join(os.path.dirname(__file__), 'dataset')


# ---------------------------------------------------------------------------
# High-frequency feature engineering
# ---------------------------------------------------------------------------

def compute_hf_features(df: pd.DataFrame) -> np.ndarray:
    """
    Build a (N, 4) feature matrix from the 6-second aggregate column.

    Channel 0 — aggregate:   raw mains power (W)
    Channel 1 — dP/dt:       per-step power difference; large values mark
                              appliance switch-on / switch-off events
    Channel 2 — rolling mean: ROLL_WIN-step local baseline (stable component)
    Channel 3 — rolling std:  ROLL_WIN-step local variability (oscillation / noise)
    """
    agg = df['aggregate'].values.astype(np.float32)

    # Rate of change — prepend 0 so length stays N
    d_agg = np.concatenate([[0.0], np.diff(agg)])

    roll     = pd.Series(agg).rolling(ROLL_WIN, min_periods=1)
    r_mean   = roll.mean().values.astype(np.float32)
    r_std    = roll.std().fillna(0.0).values.astype(np.float32)

    return np.stack([agg, d_agg, r_mean, r_std], axis=1)   # (N, 4)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_csv(split: str) -> pd.DataFrame:
    path = os.path.join(DATA_DIR, f'UKDALE_HF_{split}.csv')
    df   = pd.read_csv(path, index_col='timestamp', parse_dates=True)
    print(f"  {split:12s}: {len(df):6d} rows | {list(df.columns)}")
    return df


def create_sequences(feat: np.ndarray, targets: np.ndarray):
    """
    Seq2Point: predict appliance power at the window midpoint.

    Args:
        feat:    (N, 4)  HF feature matrix for the full day
        targets: (N, n_apps)  appliance ground truth for the full day

    Returns:
        X: (M, WIN, 4)   input windows
        Y: (M, n_apps)   midpoint targets
    """
    mid = WIN // 2
    X, Y = [], []
    for i in range(0, len(feat) - WIN, STRIDE):
        X.append(feat[i : i + WIN])
        Y.append(targets[i + mid])
    return np.array(X, dtype=np.float32), np.array(Y, dtype=np.float32)


# ---------------------------------------------------------------------------
# Physics Consistency Loss
# ---------------------------------------------------------------------------

class PhysicsConsistencyLoss(nn.Module):
    """
    One-sided Watts-domain penalty:
        L_phys = mean( ReLU( sum_i(p_hat_i_raw) - P_agg_raw - epsilon ) )

    The aggregate value at the window midpoint is the raw-Watts reference.
    Only the aggregate's MinMaxScaler params are stored (channel 0 of input).
    """

    def __init__(self, agg_scaler, y_scalers, epsilon_w: float = EPSILON_W):
        super().__init__()
        self.epsilon = epsilon_w
        self.register_buffer('x_min',
            torch.tensor(float(agg_scaler.data_min_[0]),   dtype=torch.float32))
        self.register_buffer('x_range',
            torch.tensor(float(agg_scaler.data_range_[0]), dtype=torch.float32))
        self.register_buffer('y_mins',
            torch.tensor([float(s.data_min_[0])   for s in y_scalers], dtype=torch.float32))
        self.register_buffer('y_ranges',
            torch.tensor([float(s.data_range_[0]) for s in y_scalers], dtype=torch.float32))

    def forward(self, x_mid_scaled: torch.Tensor, pred_scaled: torch.Tensor):
        """
        Args:
            x_mid_scaled: (batch,)        aggregate at midpoint, scaled
            pred_scaled:  (batch, n_apps) appliance predictions, scaled
        """
        x_raw = x_mid_scaled * self.x_range + self.x_min          # (batch,)
        p_raw = pred_scaled  * self.y_ranges + self.y_mins         # (batch, n_apps)
        return F.relu(p_raw.sum(dim=1) - x_raw - self.epsilon).mean()


# ---------------------------------------------------------------------------
# Dilated CNN pre-encoder
# ---------------------------------------------------------------------------

class DilatedCNNEncoder(nn.Module):
    """
    Three-layer dilated Conv1d encoder that compresses (batch, WIN, in_ch)
    to (batch, WIN//8, hidden) while widening the temporal receptive field.

    Dilation schedule  1 -> 2 -> 4  lets each layer see patterns at
    progressively coarser scales (individual transient, short burst, full cycle).
    """

    def __init__(self, in_ch: int, hidden: int):
        super().__init__()
        # "same" padding for dilated conv: p = dilation * (kernel - 1) // 2
        self.layers = nn.Sequential(
            # Layer 1: d=1, k=7, p=3  — captures sub-minute switching edges
            nn.Conv1d(in_ch,  hidden, kernel_size=7, padding=3,  dilation=1),
            nn.BatchNorm1d(hidden), nn.ReLU(), nn.MaxPool1d(2),

            # Layer 2: d=2, k=5, p=4  — captures ~2-min appliance phases
            nn.Conv1d(hidden, hidden, kernel_size=5, padding=4,  dilation=2),
            nn.BatchNorm1d(hidden), nn.ReLU(), nn.MaxPool1d(2),

            # Layer 3: d=4, k=3, p=4  — captures ~10-min cycle segments
            nn.Conv1d(hidden, hidden, kernel_size=3, padding=4,  dilation=4),
            nn.BatchNorm1d(hidden), nn.ReLU(), nn.MaxPool1d(2),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # (batch, WIN, in_ch) -> (batch, in_ch, WIN)
        x = x.permute(0, 2, 1)
        x = self.layers(x)           # (batch, hidden, WIN//8)
        return x.permute(0, 2, 1)    # (batch, WIN//8, hidden)


# ---------------------------------------------------------------------------
# HF Physics-Informed Liquid Network
# ---------------------------------------------------------------------------

class HFPhysicsInformedLiquidNet(nn.Module):
    """
    DilatedCNNEncoder  +  AdvancedLiquidTimeLayer  +  per-appliance heads.

    The CNN extracts multi-scale local features from the raw 6-second signal.
    The LNN propagates temporal state across the compressed sequence, modelling
    appliance duty cycles and cross-appliance dependencies.
    The physics loss is applied to the joint (batch, n_apps) output at training.
    """

    def __init__(self, in_ch: int, hidden: int, n_apps: int, dt: float = 0.1):
        super().__init__()
        self.dt     = dt
        self.hidden = hidden

        # ── CNN pre-encoder ──────────────────────────────────────────────────
        self.cnn = DilatedCNNEncoder(in_ch, hidden)

        # ── AdvancedLiquidTimeLayer (same formulation as original PINN-LNN) ──
        self.input_proj  = nn.Linear(hidden, hidden)
        self.tau_base    = nn.Parameter(torch.ones(hidden))
        self.tau_mod     = nn.Linear(hidden, hidden)
        self.rec_weights = nn.Parameter(torch.empty(hidden, hidden))
        nn.init.xavier_uniform_(self.rec_weights)
        self.gate        = nn.Linear(hidden * 2, hidden)

        # ── Output ──────────────────────────────────────────────────────────
        self.norm  = nn.LayerNorm(hidden)
        self.heads = nn.ModuleList([nn.Linear(hidden, 1) for _ in range(n_apps)])

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: (batch, WIN, in_ch)
        Returns:
            (batch, n_apps)
        """
        x = self.cnn(x)                    # (batch, T', hidden)
        batch, T, _ = x.shape
        h = torch.zeros(batch, self.hidden, device=x.device)

        for t in range(T):
            x_t = x[:, t, :]
            ip  = self.input_proj(x_t)
            rp  = h @ self.rec_weights

            tb  = F.softplus(self.tau_base).unsqueeze(0)
            tm  = torch.sigmoid(self.tau_mod(x_t))
            tau = (tb * tm).clamp(min=self.dt)

            g   = torch.sigmoid(self.gate(torch.cat([x_t, h], dim=1)))
            dh  = ((-h / tau) + g * torch.tanh(ip + rp)) * self.dt
            h   = (h + dh).clamp(-10.0, 10.0)

        h = self.norm(h)
        return torch.cat([head(h) for head in self.heads], dim=1)


# ---------------------------------------------------------------------------
# PyTorch Dataset
# ---------------------------------------------------------------------------

class MultiApplianceDataset(torch.utils.data.Dataset):
    def __init__(self, X, Y):
        self.X = torch.FloatTensor(X)
        self.Y = torch.FloatTensor(Y)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, i):
        return self.X[i], self.Y[i]


# ---------------------------------------------------------------------------
# Metrics helper
# ---------------------------------------------------------------------------

def per_app_metrics(y_true: np.ndarray, y_pred: np.ndarray, y_scalers: list) -> dict:
    out = {}
    for i, app in enumerate(APPLIANCES):
        raw_t = y_scalers[i].inverse_transform(y_true[:, i:i+1]).flatten()
        raw_p = y_scalers[i].inverse_transform(y_pred[:, i:i+1]).flatten()
        out[app] = calculate_nilm_metrics(raw_t, raw_p, threshold=THRESHOLDS[app])
    return out


# ---------------------------------------------------------------------------
# Training + evaluation
# ---------------------------------------------------------------------------

def train_hf_pinn(save_dir: str,
                  hidden: int   = 64,
                  dt:     float = 0.1,
                  lambda_phys: float = LAMBDA_PHYS,
                  epsilon_w:   float = EPSILON_W) -> tuple:

    os.makedirs(save_dir, exist_ok=True)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"\nDevice: {device}  |  WIN={WIN}  hidden={hidden}  "
          f"dt={dt}  lambda_phys={lambda_phys}  epsilon={epsilon_w} W")

    # ── Load preprocessed CSVs ───────────────────────────────────────────────
    print("\nLoading HF CSV data...")
    df_tr = load_csv('train')
    df_va = load_csv('validation')
    df_te = load_csv('test')

    # ── Compute 4-channel HF feature matrices (N, 4) ────────────────────────
    feat_tr = compute_hf_features(df_tr)
    feat_va = compute_hf_features(df_va)
    feat_te = compute_hf_features(df_te)

    # ── Appliance targets (N, n_apps) ────────────────────────────────────────
    tgt_tr = df_tr[APPLIANCES].values.astype(np.float32)
    tgt_va = df_va[APPLIANCES].values.astype(np.float32)
    tgt_te = df_te[APPLIANCES].values.astype(np.float32)

    # ── Create sliding-window sequences ──────────────────────────────────────
    X_tr, Y_tr = create_sequences(feat_tr, tgt_tr)
    X_va, Y_va = create_sequences(feat_va, tgt_va)
    X_te, Y_te = create_sequences(feat_te, tgt_te)
    print(f"\nTrain : {X_tr.shape} -> {Y_tr.shape}")
    print(f"Val   : {X_va.shape} -> {Y_va.shape}")
    print(f"Test  : {X_te.shape} -> {Y_te.shape}")

    n_feat = X_tr.shape[-1]   # 4

    # ── Scale each input channel independently (MinMaxScaler) ────────────────
    # Channel 0 (aggregate) scaler is reused by PhysicsConsistencyLoss.
    feat_scalers = []
    for ch in range(n_feat):
        sc = MinMaxScaler()
        X_tr[:, :, ch] = sc.fit_transform(
            X_tr[:, :, ch].reshape(-1, 1)).reshape(-1, WIN)
        X_va[:, :, ch] = sc.transform(
            X_va[:, :, ch].reshape(-1, 1)).reshape(-1, WIN)
        X_te[:, :, ch] = sc.transform(
            X_te[:, :, ch].reshape(-1, 1)).reshape(-1, WIN)
        feat_scalers.append(sc)
    agg_scaler = feat_scalers[0]

    # ── Scale appliance targets ───────────────────────────────────────────────
    y_scalers = []
    for i in range(len(APPLIANCES)):
        ys = MinMaxScaler()
        Y_tr[:, i:i+1] = ys.fit_transform(Y_tr[:, i:i+1])
        Y_va[:, i:i+1] = ys.transform(Y_va[:, i:i+1])
        Y_te[:, i:i+1] = ys.transform(Y_te[:, i:i+1])
        y_scalers.append(ys)

    # Scaled ON/OFF thresholds for the BCE term
    thresholds_scaled = [
        (THRESHOLDS[app] - float(y_scalers[i].data_min_[0]))
        / float(y_scalers[i].data_range_[0])
        for i, app in enumerate(APPLIANCES)
    ]

    # ── DataLoaders ──────────────────────────────────────────────────────────
    tr_ld = torch.utils.data.DataLoader(
        MultiApplianceDataset(X_tr, Y_tr), batch_size=BATCH, shuffle=True,  drop_last=False)
    va_ld = torch.utils.data.DataLoader(
        MultiApplianceDataset(X_va, Y_va), batch_size=BATCH, shuffle=False, drop_last=False)
    te_ld = torch.utils.data.DataLoader(
        MultiApplianceDataset(X_te, Y_te), batch_size=BATCH, shuffle=False, drop_last=False)

    # ── Model + losses ───────────────────────────────────────────────────────
    model = HFPhysicsInformedLiquidNet(
        in_ch=n_feat, hidden=hidden, n_apps=len(APPLIANCES), dt=dt
    ).to(device)

    mse_crit  = nn.MSELoss()
    phys_crit = PhysicsConsistencyLoss(agg_scaler, y_scalers, epsilon_w).to(device)

    opt   = torch.optim.Adam(model.parameters(), lr=LR)
    sched = torch.optim.lr_scheduler.ReduceLROnPlateau(
                opt, mode='min', factor=0.5, patience=8, min_lr=1e-5)

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Model parameters: {n_params:,}")

    history = {k: [] for k in [
        'train_loss', 'train_mse', 'train_phys',
        'val_loss',   'val_mse',   'val_phys', 'val_metrics',
    ]}
    best_val_mse = float('inf')
    best_state   = None
    counter      = 0

    print("\nStarting HF-PINN-LNN training (all appliances simultaneously)...")

    for epoch in range(EPOCHS):
        # ── Train ────────────────────────────────────────────────────────────
        model.train()
        ep_mse = ep_phys = ep_tot = 0.0
        pbar = tqdm(tr_ld, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=False)

        for xb, yb in pbar:
            xb, yb = xb.to(device), yb.to(device)
            opt.zero_grad()
            pred = model(xb)                       # (batch, n_apps)

            l_mse  = mse_crit(pred, yb)
            x_mid  = xb[:, WIN // 2, 0]           # scaled aggregate at midpoint
            l_phys = phys_crit(x_mid, pred)

            if epoch < WARMUP_EPOCHS:
                loss = l_mse
            else:
                l_bce = torch.tensor(0.0, device=device)
                for i, app in enumerate(APPLIANCES):
                    if BCE_LAMBDA[app] > 0:
                        p_i   = pred[:, i].clamp(1e-7, 1 - 1e-7)
                        thr_s = thresholds_scaled[i]
                        y_bin = (yb[:, i] > thr_s).float()
                        w     = torch.where(y_bin == 1,
                                            torch.full_like(y_bin, BCE_ALPHA[app]),
                                            torch.ones_like(y_bin))
                        l_bce = l_bce + BCE_LAMBDA[app] * F.binary_cross_entropy(
                                    p_i, y_bin, weight=w)
                loss = l_mse + lambda_phys * l_phys + l_bce

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()

            ep_mse  += l_mse.item()
            ep_phys += l_phys.item()
            ep_tot  += loss.item()
            pbar.set_postfix({'mse': f'{l_mse.item():.5f}',
                              'phys': f'{l_phys.item():.5f}'})

        history['train_mse'].append(ep_mse  / len(tr_ld))
        history['train_phys'].append(ep_phys / len(tr_ld))
        history['train_loss'].append(ep_tot  / len(tr_ld))

        # ── Validate ─────────────────────────────────────────────────────────
        model.eval()
        vl_mse = vl_phys = vl_tot = 0.0
        vp_all, vt_all = [], []

        with torch.no_grad():
            for xb, yb in va_ld:
                xb, yb = xb.to(device), yb.to(device)
                pred   = model(xb)
                l_mse  = mse_crit(pred, yb)
                x_mid  = xb[:, WIN // 2, 0]
                l_phys = phys_crit(x_mid, pred)
                vl_mse  += l_mse.item()
                vl_phys += l_phys.item()
                vl_tot  += (l_mse + lambda_phys * l_phys).item()
                vp_all.append(pred.cpu().numpy())
                vt_all.append(yb.cpu().numpy())

        avg_va_mse  = vl_mse  / len(va_ld)
        avg_va_phys = vl_phys / len(va_ld)
        avg_va_tot  = vl_tot  / len(va_ld)
        history['val_mse'].append(avg_va_mse)
        history['val_phys'].append(avg_va_phys)
        history['val_loss'].append(avg_va_tot)
        sched.step(avg_va_mse)

        y_pred_va = np.concatenate(vp_all)
        y_true_va = np.concatenate(vt_all)
        vm = per_app_metrics(y_true_va, y_pred_va, y_scalers)
        history['val_metrics'].append(vm)

        avg_f1  = np.mean([vm[a]['f1']  for a in APPLIANCES])
        avg_mae = np.mean([vm[a]['mae'] for a in APPLIANCES])
        tr_mse  = history['train_mse'][-1]
        tr_phys = history['train_phys'][-1]
        tr_tot  = history['train_loss'][-1]

        print(
            f"  Epoch {epoch+1:3d}/{EPOCHS}  "
            f"train={tr_tot:.5f} (mse={tr_mse:.5f} phys={tr_phys:.5f})  "
            f"val={avg_va_tot:.5f} (mse={avg_va_mse:.5f} phys={avg_va_phys:.5f})  "
            f"avgF1={avg_f1:.4f}  avgMAE={avg_mae:.2f}  "
            f"lr={opt.param_groups[0]['lr']:.2e}"
        )
        for app in APPLIANCES:
            m = vm[app]
            print(f"    {app:<22}  F1={m['f1']:.4f}  P={m['precision']:.4f}  "
                  f"R={m['recall']:.4f}  MAE={m['mae']:.2f}  SAE={m['sae']:.4f}")

        # Early stopping on val MSE (physics oscillations are excluded)
        if avg_va_mse < best_val_mse:
            best_val_mse = avg_va_mse
            best_state   = {k: v.clone() for k, v in model.state_dict().items()}
            counter      = 0
        else:
            counter += 1
            if counter >= PATIENCE:
                print(f"  Early stopping at epoch {epoch+1}")
                break

    print("\nTraining complete.")

    # ── Test evaluation ───────────────────────────────────────────────────────
    if best_state is not None:
        model.load_state_dict(best_state)
    model.eval()

    tp_all, tt_all = [], []
    with torch.no_grad():
        for xb, yb in te_ld:
            tp_all.append(model(xb.to(device)).cpu().numpy())
            tt_all.append(yb.cpu().numpy())

    y_pred_te = np.concatenate(tp_all)
    y_true_te = np.concatenate(tt_all)
    test_metrics = per_app_metrics(y_true_te, y_pred_te, y_scalers)

    print(f"\n{'Appliance':<24} {'F1':>8} {'Precision':>10} "
          f"{'Recall':>8} {'MAE':>8} {'SAE':>8}")
    print("-" * 72)
    for app in APPLIANCES:
        m = test_metrics[app]
        print(f"{app:<24} {m['f1']:>8.4f} {m['precision']:>10.4f} "
              f"{m['recall']:>8.4f} {m['mae']:>8.2f} {m['sae']:>8.4f}")

    # ── Plots ─────────────────────────────────────────────────────────────────
    _plot(history, test_metrics, save_dir)

    # ── Save JSON summary ─────────────────────────────────────────────────────
    cfg = {
        'dataset':     'UKDALE HF 6s',
        'model':       'HFPhysicsInformedLiquidNet',
        'description': 'DilatedCNNEncoder + AdvancedLiquidTimeLayer + PhysicsLoss',
        'hf_features': ['aggregate', 'dP_dt', 'rolling_mean_10s', 'rolling_std_10s'],
        'window_size': WIN,
        'stride':      STRIDE,
        'roll_win':    ROLL_WIN,
        'model_params': {
            'in_ch': n_feat, 'hidden': hidden,
            'n_apps': len(APPLIANCES), 'dt': dt,
        },
        'train_params': {
            'lr': LR, 'epochs': EPOCHS, 'patience': PATIENCE,
            'lambda_phys': lambda_phys, 'epsilon_w': epsilon_w,
            'warmup_epochs': WARMUP_EPOCHS,
        },
        'test_metrics': {
            app: {k: float(v) for k, v in m.items()}
            for app, m in test_metrics.items()
        },
    }
    json_path = os.path.join(save_dir, 'hf_pinn_lnn_results.json')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(cfg, f, indent=4)
    print(f"\nResults saved to {save_dir}")

    return test_metrics, history


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def _plot(history: dict, test_metrics: dict, save_dir: str) -> None:
    ep = range(1, len(history['train_loss']) + 1)

    # Loss curves
    plt.figure(figsize=(15, 4))
    for idx, (tr_k, va_k, title) in enumerate([
        ('train_loss',  'val_loss',  'Total Loss (MSE + phys)'),
        ('train_mse',   'val_mse',   'MSE Loss'),
        ('train_phys',  'val_phys',  'Physics Consistency Loss'),
    ]):
        plt.subplot(1, 3, idx + 1)
        plt.plot(ep, history[tr_k], label='Train', color='steelblue')
        plt.plot(ep, history[va_k], label='Val',   color='tomato')
        plt.title(title); plt.xlabel('Epoch')
        plt.legend(); plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'hf_pinn_lnn_loss.png'),
                dpi=150, bbox_inches='tight')
    plt.close()

    # Per-appliance F1 / MAE validation curves
    fig, axes = plt.subplots(len(APPLIANCES), 2,
                             figsize=(12, 4 * len(APPLIANCES)))
    fig.suptitle('HF-PINN-LNN UKDALE — Per-Appliance Validation Metrics', fontsize=13)
    for row, app in enumerate(APPLIANCES):
        f1s  = [m[app]['f1']  for m in history['val_metrics']]
        maes = [m[app]['mae'] for m in history['val_metrics']]

        ax_f1  = axes[row][0]
        ax_mae = axes[row][1]

        ax_f1.plot(ep, f1s, color='steelblue', linewidth=1.5)
        ax_f1.axhline(test_metrics[app]['f1'], color='green',
                      linestyle='--', linewidth=1.2, label='Test F1')
        ax_f1.set_title(f'{app} — F1')
        ax_f1.set_xlabel('Epoch'); ax_f1.set_ylabel('F1')
        ax_f1.legend(); ax_f1.grid(alpha=0.3)

        ax_mae.plot(ep, maes, color='tomato', linewidth=1.5)
        ax_mae.axhline(test_metrics[app]['mae'], color='green',
                       linestyle='--', linewidth=1.2, label='Test MAE')
        ax_mae.set_title(f'{app} — MAE (W)')
        ax_mae.set_xlabel('Epoch'); ax_mae.set_ylabel('MAE (W)')
        ax_mae.legend(); ax_mae.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, 'hf_pinn_lnn_per_appliance.png'),
                dpi=150, bbox_inches='tight')
    plt.close()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    for split in ['train', 'validation', 'test']:
        p = os.path.join(DATA_DIR, f'UKDALE_HF_{split}.csv')
        if not os.path.exists(p):
            print(f"Error: {p} not found. Run preprocess_hf.py first.")
            sys.exit(1)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    save_dir  = f'models/hf_pinn_lnn_{timestamp}'

    train_hf_pinn(
        save_dir    = save_dir,
        hidden      = 64,
        dt          = 0.1,
        lambda_phys = LAMBDA_PHYS,
        epsilon_w   = EPSILON_W,
    )
